config/routes.rb
Rails.application.routes.draw do
  root "videos#index"
  resources :videos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :subject

  validates :title, :uniqueness => { message: "must be unique inside one specific topic/subject", scope: :subject_id }

  def self.search(search_param: nil)
    if search_param
      query = sanitize_sql_for_assignment(["title ILIKE ?","%#{search_param}%"])
      where(query)
    else
      all
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.search(search_param: params[:search_field]).paginate(page: page, per_page: per_page)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :subject_id)
    end

    def page
      params[:page].try(:to_i) || 1
    end

    def per_page
      params[:per_page].try(:to_i) || 10
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_main_layout.html.erb
<div class="warnings">
  <div class="grid-row">
    <div class="grid-column-12">
    </div>
  </div>
</div>
<div class="page-header">
  <div class="page-header__sofatutor grid-row">
    <nav class="page-header-main__nav">
      <div class="page-header-main__logo">
        <a class="page-header__logo" data-turbolinks="false" href="#" rel="start" title="Online-Nachhilfe in Mathe, Deutsch, Englisch u. v. m. | sofatutor"></a>
      </div>
      <a class="page-header__menu">
        <span></span>
        <span></span>
        <span></span>
      </a>
      <ul class="page-header-main__list page-header-main__list--phones js-mobile-main-list" style="display: none">
        <li class="page-header-main__item page-header-main__item--login">
          <a class="page-header-main__link" href="#">Login</a>
        </li>
        <li class="page-header-main__item page-header-main__item--subjects">
          <a class="page-header-main__link page-header-main__features-link" href="#">Schulfächer</a>
        </li>
        <li class="page-header-main__item page-header-main__item--features">
          <a class="page-header-main__link page-header-main__features-link" href="#">So geht's</a>
        </li>
        <li class="page-header-main__item page-header-main__item--information">
          <a class="page-header-main__link" data-tracking-action="about_us_open" href="#">Infos</a>
        </li>
        <li class="page-header-main__item page-header-main__item--guided-tour">
          <a class="page-header-main__link" href="#"><span class="show-for-large">Für</span> Lehrkräfte &amp; Schulen</a>
        </li>
        <li class="page-header-main__item page-header-main__item--pricing">
          <a class="page-header-main__link" href="#">Preise</a>
        </li>
      </ul>
      <ul class="page-header-main__list page-header-main__list--default">
        <li class="page-header-main__item page-header-main__item--subjects toggle-subjects-menu js-dropdown-toggle">
          <a class="page-header-main__link page-header-main__link--arrow js-pin-dropdown" href="#">
            Schulfächer
          </a>
        </li>
        <li class="page-header-main__item page-header-main__item--features js-dropdown-toggle">
          <a class="page-header-main__link page-header-main__features-link js-pin-dropdown" href="#">So geht's</a>
        </li>
        <li class="page-header-main__item page-header-main__item--information js-dropdown-toggle">
          <a class="page-header-main__link js-pin-dropdown" data-tracking-action="about_us_open" href="#">Infos</a>
        </li>
        <li class="page-header-main__item page-header-main__item--guided-tour">
          <a class="page-header-main__link" href="#"><span class="show-for-large">Für</span> Lehrkräfte &amp; Schulen</a>
        </li>
        <li class="page-header-main__item page-header-main__item--pricing">
          <a class="page-header-main__link" href="#">Preise</a>
        </li>
      </ul>
    </nav>
    <nav class="page-header-sub-nav">
      <ul class="page-header-sub-nav__list">
        <li class="page-header-sub-nav__item show-for-large">
          <a class="button small yellow trial-header-button" href="#">Kostenlos testen</a>
        </li>
        <li class="page-header-login open-login page-header-sub-nav__item js-dropdown-toggle">
          <a class="page-header-login__link page-header__button js-pin-dropdown" href="#">Login</a>
          <div class="page-header-flyout page-header-login__dropdown page-header-sub-nav__dropdown js-dropdown" style="overflow-y: initial; height: auto;">
            <div class="page-header-flyout__title">Du hast bereits einen Account?</div>
            <div class="page-header-flyout__subtitle">Logge dich ein:</div>
            <div class="page-header-login__form">
              <form class="new_user" id="new_user" action="/session" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="BjBUa10IkHBxCTK8tteOQxZQrQRFkLJZDibnkdz2lSoGY81TrNRNxog5zdGztfbEOlPHpTPvsIvSKSJXTF7mXA" autocomplete="off"><input class="this-path-field" name="error_return_to" type="hidden">
                <input class="this-path-field" name="return_to" type="hidden">
                <div class="email">
                  <label for="user_email">Deine E-Mail-Adresse</label>
                  <input type="email" name="user[email]" id="user_email">
                </div>
                <div class="password">
                  <label for="user_password">Dein Passwort</label>
                  <input type="password" name="user[password]" id="user_password">
                </div>
                <div class="page-header-password-forgotten">
                  <a class="page-header-password-forgotten__link" href="#">Passwort vergessen</a>
                </div>
                <input type="submit" name="commit" value="Einloggen" class="button medium primary" data-disable-with="Einloggen">
              </form>
            </div>
            <div class="student-code-box">
              <div class="h5 student-code-box__title">Du hast einen <b>Code von deiner Lehrkraft</b> erhalten? Trage ihn hier ein:</div>
              <form action="/student_code_login" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="BjBUa10IkHBxCTK8tteOQxZQrQRFkLJZDibnkdz2lSoGY81TrNRNxog5zdGztfbEOlPHpTPvsIvSKSJXTF7mXA" autocomplete="off">
                <label class="student-code-box__label" for="student_code">Zugangscode</label>
                <div class="flex-container">
                  <input type="text" name="student_code" id="student_code" class="student-code-box__text-field">
                  <input type="submit" name="commit" value="Los!" class="student-code-box__button button medium orange " data-disable-with="Los!">
                </div>
              </form>
            </div>
          </div>
        </li>
      </ul>
    </nav>
  </div>
</div>
<div class="page-banners js-page-banner">
  <a class="page-banner page-banner--default" href="#" data-turbolinks="false" data-banner-type="default">
    <div class="grid-container">
      <div class="grid-x grid-padding-x">
        <button class="" href="#" data-turbolinks="false"><i class="page-banner__cta-arrow show-for-small-only"></i>
        </button>
        <div class="media-object page-banner__content cell small-11 large-9 medium-8">
          <div class="media-object-section">
            <i aria-label="" class="page-banner__icon" role="img"></i>
          </div>
          <div class="media-object-section">
            <b class="h5 page-banner__headline"><b>30 Tage kostenlos testen</b></b>
            <p class="h6 page-banner__text show-for-medium banner_msg"></p>
            <p class="h6 page-banner__text show-for-small-only"></p>
          </div>
        </div>
        <div class="cell medium-4 large-3 page-banner__content show-for-medium">
          <button class="page-banner__side-content page-banner__button button medium primary" data-turbolinks="false" type="button" onclick="switchCookie()">Jetzt zugreifen
          </button></div>
      </div>
    </div>
  </a>
</div>
<div class="page-content" id="page-content">
  <div class="visitors-video-page">
    <div class="videos-title">
      <div class="grid-container">
        <h1 class="h2 videos-title__headline">Demo video search</h1>
      </div>
    </div>
    <div class="videos-conversion-buttons-container">
      <div class="grid-container videos-conversion-buttons">
        <button class="flex-container videos-conversion-button videos-conversion-button--video js-video-conversion-button">
          <i class="flex-container align-center-middle videos-conversion-button__icon videos-conversion-button__icon--video">
            <svg height="20" viewBox="0 0 30 20" width="30" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="m28.5 20h-27c-.8 0-1.5-.7-1.5-1.5v-17c0-.8.7-1.5 1.5-1.5h27c.8 0 1.5.7 1.5 1.5v17c0 .8-.7 1.5-1.5 1.5" fill="#fff"></path><path d="m12 6v8l7-4z" fill="#690"></path></g></svg>
          </i>
          <p class="videos-conversion-button__text"><b>Videos</b><br>
            anschauen</p>
        </button>
        <button class="flex-container videos-conversion-button videos-conversion-button--exercise js-exercise-conversion-button">
          <i class="flex-container align-center-middle videos-conversion-button__icon videos-conversion-button__icon--exercise">
            <svg height="27" viewBox="0 0 30 27" width="30" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="m7.3 18-7 7 6 2 4-4z" fill="#c9a400"></path><path d="m16.3 0-12.9 12.9c-.6.6-.6 1.5 0 2.1l1.9 2-3 3 7 7 3-3 1.9 1.9c.6.6 1.5.6 2.1 0l13-12.9z" fill="#fff"></path></g></svg>
          </i>
          <p class="videos-conversion-button__text"><b>Übungen</b><br>
            starten</p>
        </button>
        <button class="flex-container videos-conversion-button videos-conversion-button--worksheet js-worksheet-conversion-button">
          <i class="flex-container align-center-middle videos-conversion-button__icon videos-conversion-button__icon--worksheet">
            <svg height="26" viewBox="0 0 20 26" width="20" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="m1.5 0c-.8 0-1.5.7-1.5 1.5v23c0 .8.7 1.5 1.5 1.5h17c.8 0 1.5-.7 1.5-1.5v-18.5l-6-6z" fill="#fff"></path><g fill="#e66"><path d="m12 13v-3h-4v3h-2.6l4.6 4 4.5-4z"></path><path d="m20 6-6-6v4.5c0 .8.7 1.5 1.5 1.5z"></path></g></g></svg>
          </i>
          <p class="videos-conversion-button__text"><b>Arbeits&shy;blätter</b><br>
            anzeigen</p>
        </button>
        <button class="flex-container videos-conversion-button videos-conversion-button--chat js-chat-conversion-button">
          <i class="flex-container align-center-middle videos-conversion-button__icon videos-conversion-button__icon--chat">
            <svg height="24" viewBox="0 0 30 24" width="30" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="m0 12.1c0 6.5 6.3 11.9 14 11.9h16s-4.2-2.1-3.5-6.6c.1-.6.3-1.2.6-1.8.5-1.1 1-2.6 1-3.5 0-6.6-6.3-12.1-14.1-12.1s-14 5.5-14 12.1z" fill="#fff"></path><g fill="#0088b5"><path d="m16 9h-7c-.6 0-1-.4-1-1 0-.6.4-1 1-1h7c.6 0 1 .4 1 1 0 .6-.4 1-1 1z"></path><path d="m19 13h-10c-.6 0-1-.4-1-1 0-.6.4-1 1-1h10c.6 0 1 .4 1 1 0 .6-.4 1-1 1z"></path><path d="m17 17h-8c-.6 0-1-.4-1-1 0-.6.4-1 1-1h8c.6 0 1 .4 1 1 0 .6-.4 1-1 1z"></path></g></g></svg>
          </i>
          <p class="videos-conversion-button__text"><b>Lehrer*&ZeroWidthSpace;innen</b><br>
            fragen</p>
        </button>
      </div>
    </div>
  </div>
</div>
</div>
<div class="simple-lightbox bg-black-transparent js-exit-intent-overlay show-for-large" style="display: none;"></div>

<script type="text/javascript">
  checkCookie();

  function getCookie(cname) {
    let name = cname + "=";
    let decodedCookie = decodeURIComponent(document.cookie);
    let ca = decodedCookie.split(';');

    for(let i = 0; i <ca.length; i++) {
      let c = ca[i];
      while (c.charAt(0) == ' ') {
        c = c.substring(1);
      }
      if (c.indexOf(name) == 0) {
        return c.substring(name.length, c.length);
      }
    }

    return "";
  };

  function checkCookie() {
    if (getCookie("banner_value") === '') {
      document.cookie = "banner_value = 0";
    }

    let banner_value = getCookie("banner_value");
    var text = {
        0:"Überzeugen Sie sich von der Qualität unserer Inhalte.",
        1:"Jetzt ganz einfach den Schulstoff nachholen und 30% sparen!"
    }

    document.querySelector(".banner_msg").innerText = text[banner_value];
  };

  function switchCookie() {
    if (getCookie("banner_value") == 0) {
      document.cookie = "banner_value = 1";
    } else {
      document.cookie = "banner_value = 0";
    };

    checkCookie();
  };
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sofatutor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" media="all" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400italic,600,600italic,700&amp;display=swap" onload="this.media=&quot;all&quot;">
  </head>

  <body class="is-responsive is-elementary locale-de">
    <%= render 'layouts/main_layout' %>
    <%= yield %>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subject_id %>
    <%= form.text_field :subject_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<header class="search-content-header">
  <div class="grid-row search-responsive-grid">
    <%= form_tag({:controller => "videos", :action => "index"}, :method => :get) do %>
      <div class="grid-column-11">
        <div class="search-form" id="instant-search-form">
          <%= text_field_tag "search_field", params[:search_field], class: "search-form__input", placeholder: "Suche nach Videotitel...", autocomplete: :off %>
          <div id="search-state-helpers"><button class="clear-icon sprites-search sprites-search--close" id="search-input-clear"></button></div>
        </div>
      </div>
      <div class="grid-column-1">
        <%= button_tag :submit, class: "button medium white search__button" do %>
          <i class='icon icon--small icon--search'></i>
        <% end %>
      </div>
    <% end %>
  </div>
</header>
<div class="search-results">
  <div class="grid-row">
    <div class="grid-column-12">
      <div class="subject-box">
        <% if @videos.present? %>
          <% @videos.group_by { |t| t.subject.subject_name }.each do |subject, videos| %>
            <div class="subject-box subject-box__content">
              <h3 class="h4 subject-box__header">
                <i class="sprites-subjects-64--<%=subject.downcase%> subject-box__icon"></i>
                <b class="subject-box__title"> <%= subject %> </b>
              </h3>
              <ul class="search-result-list">
                <% videos.each do |video| %>
                  <li class="search-result-list__item search-result-list__item--bookmarkable">
                    <a class="search-result-list__item-link" href="#">
                      <div class="search-result-list__item-thumbnail">
                        <img class="search-result-list__item-image" src="/assets/video-thumbnail.png">
                        <i class="icon secondary search-result-list__item-icon icon--video"></i>
                      </div>
                      <div class="search-result-list__item-description">
                        <div class="h5 search-result-list__item-title"><%= video.title %></div>
                        <div class="grid-x search-result-list__item-meta-details">
                          <div class="video-icons">
                            <div class="search-result-list__item-meta-detail">
                              <i class="icon icon--small icon--video-duration"></i>
                              <span>3:<%= rand(0..5).to_s+rand(0..9).to_s %> min</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                  </li>
                <% end %>
              </ul>
            </div>
            <br>
          <% end %>
        <% else %>
          <h4> No results. </h4>
        <% end %>
        <div class="h4 digg_pagination ">
          <%= will_paginate @videos %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @video.subject_id %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>